"""create order management tables

Revision ID: bb3014f7d580
Revises: 2a6d2efb8667
Create Date: 2026-07-26 10:57:40.148705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3014f7d580'
down_revision: Union[str, Sequence[str], None] = '2a6d2efb8667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_orders',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seller_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_orders_buyer_id'), 'buyer_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_order_number'), 'buyer_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_buyer_orders_status'), 'buyer_orders', ['status'], unique=False)
    op.create_table('address_snapshots',
    sa.Column('buyer_order_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.Enum('HOME', 'WORK', 'OTHER', name='addresstype'), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_snapshots_buyer_order_id'), 'address_snapshots', ['buyer_order_id'], unique=True)
    op.create_table('payments',
    sa.Column('buyer_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('gateway', sa.Enum('RAZORPAY', 'STRIPE', 'PAYPAL', 'CASHFREE', name='paymentgateway'), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', 'OTHER', name='paymentmethod'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_order_id'),
    sa.UniqueConstraint('gateway_payment_id'),
    sa.UniqueConstraint('gateway_transaction_reference')
    )
    op.create_index(op.f('ix_payments_buyer_order_id'), 'payments', ['buyer_order_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('seller_orders',
    sa.Column('buyer_order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='sellerorderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seller_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_orders_buyer_order_id'), 'seller_orders', ['buyer_order_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_seller_id'), 'seller_orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_orders_status'), 'seller_orders', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('seller_order_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('purchase_source', sa.Enum('LISTING', 'OFFER', 'AUCTION', 'RESERVATION', name='purchasesource'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('listing_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offer_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_listing_id'), 'order_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_order_items_purchase_source'), 'order_items', ['purchase_source'], unique=False)
    op.create_index(op.f('ix_order_items_seller_order_id'), 'order_items', ['seller_order_id'], unique=False)
    op.create_table('payouts',
    sa.Column('seller_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'HOLD', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('marketplace_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_gateway_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_reference')
    )
    op.create_index(op.f('ix_payouts_seller_order_id'), 'payouts', ['seller_order_id'], unique=True)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('return_requests',
    sa.Column('seller_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'PICKUP_SCHEDULED', 'PICKED_UP', 'RECEIVED', 'COMPLETED', 'CANCELLED', name='returnstatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('seller_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_approved_by'), 'return_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_return_requests_seller_order_id'), 'return_requests', ['seller_order_id'], unique=True)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_table('shipments',
    sa.Column('seller_order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY_TO_SHIP', 'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED', name='shipmentstatus'), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('carrier_tracking_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_order_id'], ['seller_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_shipments_seller_order_id'), 'shipments', ['seller_order_id'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED', name='refundstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('RETURN_APPROVED', 'ORDER_CANCELLATION', 'PAYMENT_FAILURE', 'GOODWILL', 'OTHER', name='refundreason'), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_refund_id'),
    sa.UniqueConstraint('gateway_transaction_reference')
    )
    op.create_index(op.f('ix_refunds_reason'), 'refunds', ['reason'], unique=False)
    op.create_index(op.f('ix_refunds_return_request_id'), 'refunds', ['return_request_id'], unique=True)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('return_items',
    sa.Column('return_request_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('DAMAGED', 'DEFECTIVE', 'WRONG_ITEM', 'WRONG_SIZE', 'NOT_AS_DESCRIBED', 'QUALITY_ISSUE', 'CHANGED_MIND', 'OTHER', name='returnreason'), nullable=False),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('inspection_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_order_item_id'), 'return_items', ['order_item_id'], unique=True)
    op.create_index(op.f('ix_return_items_reason'), 'return_items', ['reason'], unique=False)
    op.create_index(op.f('ix_return_items_return_request_id'), 'return_items', ['return_request_id'], unique=False)
    op.alter_column('listings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_seller_applications_reviewed_by'), table_name='seller_applications')
    op.drop_index(op.f('ix_sellers_application_id'), table_name='sellers')
    op.drop_constraint(op.f('sellers_application_id_key'), 'sellers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sellers_application_id_key'), 'sellers', ['application_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sellers_application_id'), 'sellers', ['application_id'], unique=True)
    op.create_index(op.f('ix_seller_applications_reviewed_by'), 'seller_applications', ['reviewed_by'], unique=False)
    op.alter_column('listings', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_return_items_return_request_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_reason'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_order_item_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_return_request_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_reason'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_seller_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_seller_order_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_approved_by'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_seller_order_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_order_items_seller_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_purchase_source'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_listing_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_seller_orders_status'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_seller_id'), table_name='seller_orders')
    op.drop_index(op.f('ix_seller_orders_buyer_order_id'), table_name='seller_orders')
    op.drop_table('seller_orders')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_buyer_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_address_snapshots_buyer_order_id'), table_name='address_snapshots')
    op.drop_table('address_snapshots')
    op.drop_index(op.f('ix_buyer_orders_status'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_order_number'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_buyer_id'), table_name='buyer_orders')
    op.drop_table('buyer_orders')
    # ### end Alembic commands ###
