"""add variant type to products

Revision ID: cd3ef6afccac
Revises: 1fc8a1fd70c4
Create Date: 2026-07-24 11:15:42.440255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3ef6afccac'
down_revision: Union[str, Sequence[str], None] = '1fc8a1fd70c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_types_name'), 'variant_types', ['name'], unique=True)
    op.create_table('variant_options',
    sa.Column('variant_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_value', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_type_id'], ['variant_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_type_id', 'code', name='uq_variant_type_option_code')
    )
    op.create_index(op.f('ix_variant_options_variant_type_id'), 'variant_options', ['variant_type_id'], unique=False)
    op.add_column('products', sa.Column('variant_type_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_variant_type_id'), 'products', ['variant_type_id'], unique=False)
    op.create_foreign_key(None, 'products', 'variant_types', ['variant_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_variant_type_id'), table_name='products')
    op.drop_column('products', 'variant_type_id')
    op.drop_index(op.f('ix_variant_options_variant_type_id'), table_name='variant_options')
    op.drop_table('variant_options')
    op.drop_index(op.f('ix_variant_types_name'), table_name='variant_types')
    op.drop_table('variant_types')
    # ### end Alembic commands ###
